name:                hindley-milner
version:             0.0.0
github:              "arendsee/hindley-milner"
license:             MIT
author:              "Zebulun Arendsee"
maintainer:          "zbwrnz@gmail.com"
copyright:           "2019 Zebulun Arendsee"
extra-source-files:
    - README.md
description:         Please see the README on GitHub at <https://github.com/arendsee/hindley-milner#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- prettyprinter
- prettyprinter-ansi-terminal

default-extensions:
  - OverloadedStrings
  - FlexibleInstances

library:
  source-dirs: src

executables:
  hindley-milner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hindley-milner
