name:                xi
version:             0.1.0
github:              "morloc-project/xi"
license:             MIT
author:              "Zebulun Arendsee"
maintainer:          "zbwrnz@gmail.com"
copyright:           "2019 Zebulun Arendsee"
extra-source-files:
    - README.md
    - TODO
    - USAGE
description:         Please see the README on GitHub at <https://github.com/morloc-project/xi#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- text
- megaparsec
- QuickCheck
- prettyprinter
- prettyprinter-ansi-terminal
- extra
- scientific

default-extensions:
  - OverloadedStrings
  - FlexibleInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind

library:
  source-dirs: src

executables:
  xi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xi
    - docopt
    - filepath

tests:
  xi-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - xi
      - tasty
      - tasty-quickcheck
      - tasty-hunit
