= xi experimental type system
:source-highlighter: pygments
:pygments-style: emacs
:bibtex-file: references.bib
:bibtex-style: cambridge-university-press-numeric.csl
:bibtex-order: appearance

The type system presented below is based on the one developed be Dunfield and
Krishnaswami cite:[dunfield2013complete]. The sets of rules below, except where
indicated, are taken directly from their paper.

[env.texmacro]
--
\def\ea{\widehat{\alpha}}
\def\eb{\widehat{\beta}}
\newcommand{\mark}[1]{\blacktriangleright_{#1}}
\newcommand{\expr}[3]{#1\ \vdash\ #2\ \dashv\ #3}
--

== Grammar

terms:: $e\ :=\ ()\ |\ x\ |\ \lambda x .\ e\ |\ e e\ |\ e\ :\ A\ |\ x=e\ ;\ e\ |\ x\ ::\ A\ ; e$
types:: $A,B,C\ :=\ 1\ |\ \alpha\ |\ A \rightarrow B\ |\ \forall \alpha. A\ |\ \alpha\ A$

== Algorithmic Rules

=== Subtyping and instantiation

.Subtyping Rules
|===
^| $\frac{}{\expr{\Gamma[\alpha\]}{\alpha\ <:\ \alpha}{\Gamma[\alpha\]}}$ [green]+<:Var+
  $\quad\quad$
  $\frac{}{\expr{\Gamma}{1\ <:\ 1}{\Gamma}}$ [green]+<:Unit+
  $\quad\quad$
  $\frac{}{\expr{\Gamma[\ea\]}{\ea\ <:\ \ea\}{\Gamma[\ea\]}}$ [green]+<:Exvar+
  +
  +
  $\frac{\expr{\Gamma}{B_1\ <:\ A_1}{\Theta} \quad \expr{\Theta}{[\Theta\]A_2\ <:\ [\Theta\]B_2}{\Delta}}{\expr{\Gamma}{A_1 \rightarrow A_2\ <:\ B_1 \rightarrow B_2}{\Delta}}$ [green]+<:→+
  +
  +
  $\frac{A_1\ <:\ B_1 \quad A_2\ <:\ B_2}{\expr{\Gamma}{A_1\ A_2\ <:\ B_1\ B_2}{\Delta}}$ [blue]+<:App+
  +
  +
  $\frac{\expr{\Gamma,\mark{\ea},\ea}{[\ea/\alpha\]A\ <:\ B}{\Delta,\mark{\ea},\Theta}}{\expr{\Gamma}{\forall \alpha . A\ <:\ B}{\Delta}}$ [green]+<:∀L+
  $\quad\quad$
  $\frac{\expr{\Gamma,\alpha}{A<:B}{\Delta,\alpha,\Theta}}{\expr{\Gamma}{A <: \forall \alpha . B}{\Delta}}$ [green]+<:∀R+
  +
  +
  $\frac{\ea \notin FV(A) \quad \expr{\Gamma[\ea\]}{\ea\ :\leqq\ A}{\Delta}}{\expr{\Gamma[\ea\]}{\ea\ <:\ A}{\Delta}}$ [green]+<:InstantiateL+
  $\quad\quad$
  $\frac{\ea \notin FV(A) \quad \expr{\Gamma[\ea\]}{A\ :\leqq\ \ea}{\Delta}}{\expr{\Gamma[\ea\]}{A\ <:\ \ea}{\Delta}}$ [green]+<:InstantiateR+
>| $\text{subtype} :: A \rightarrow B \rightarrow \Gamma \rightarrow \Delta$
|===


.Instantiation Rules
|===
^| $\frac{\Gamma\ \vdash\ \tau}{\expr{\Gamma,\ea,\Gamma'}{\ea\ :\leqq\ \tau}{\Gamma,\ea=\tau,\Gamma'}}$ [green]+InstLSolve+
   $\quad\quad$
   $\frac{}{\expr{\Gamma[\ea\][\eb\]}{\ea :\leqq \eb}{\Gamma[\ea\][\eb=\ea\]}}$ [green]+InstLReach+
   +
   +
   $\frac{\expr{\Gamma[\ea_2,\ea_1,\ea=\ea_2\rightarrow\ea_1\]}{A_1 :\leqq \ea_1}{\Theta} \quad \expr{\Theta}{\ea_2 :\leqq [\Theta\]A_2}{\Delta}}{\expr{\Gamma[\ea\]}{\ea\ :\leqq\ A_1 \rightarrow A_2}{\Delta}}$ [green]+InstLArr+
   $\quad\quad$
   $\frac{\expr{\Gamma[\ea\],\beta}{\ea\ :\leqq\ B}{\Delta,\beta,\Delta'}}{\expr{\Gamma[\ea}{\ea\ :\leqq\ \forall \beta . B}{\Delta}}$ [green]+InstLAllR+
^| $\frac{\Gamma\ \vdash\ \tau}{\expr{\Gamma,\ea,\Gamma'}{\tau\ :\leqq\ \ea}{\Gamma,\ea=\tau,\Gamma'}}$ [green]+InstRSolve+
   $\quad\quad$
   $\frac{}{\expr{\Gamma[\ea\][\eb\]}{\eb :\leqq \ea}{\Gamma[\ea\][\eb=\ea\]}}$ [green]+InstRReach+
   +
   +
   $\frac{\expr{\Gamma[\ea_2,\ea_1,\ea=\ea_2\rightarrow\ea_1\]}{\ea_1 :\leqq A_1}{\Theta}  \quad  \expr{\Theta}{[\Theta\]A_2 :\leqq \ea_2}{\Delta}}{\expr{\Gamma[\ea\]}{A_1 \rightarrow A_2\ :\leqq\ \ea}{\Delta}}$ [green]+InstRArr+
   $\quad\quad$
   $\frac{\Gamma[\widehat{\alpha}\],\blacktriangleright \widehat{\beta},\widehat{\beta}\ \vdash [\widehat{\beta}/\beta\]B\ :\leqq\ \widehat{\alpha}\ \dashv\ \Delta,\blacktriangleright \widehat{\beta},\Delta'}{\Gamma[\widehat{\alpha}\ \vdash\ \forall \beta . B\ :\leqq\ \widehat{\alpha}\ \dashv\ \Delta}$ [green]+InstRAllL+
>| $\text{instantiate}\ ::\ A \rightarrow B \rightarrow \Gamma \rightarrow \Delta$
|===

=== Typechecking rules -- bidirectional or tridirectional?

.infer
|===
^| $\frac{}{\expr{\Gamma}{\text{number} \Rightarrow \text{Num}}{\Gamma}}$ [blue]+Num⇒+
   $\quad\quad$
   $\frac{}{\expr{\Gamma}{\text{int} \Rightarrow \text{Int}}{\Gamma}}$ [blue]+Int⇒+
   $\quad\quad$
   $\frac{}{\expr{\Gamma}{\text{string} \Rightarrow \text{Str}}{\Gamma}}$ [blue]+Str⇒+
   $\quad\quad$
   $\frac{}{\expr{\Gamma}{\text{bool} \Rightarrow \text{Bool}}{\Gamma}}$ [blue]+Bool⇒+
   +
   +
   $\frac{v \notin \text{FV}(\Gamma) \quad \expr{\Gamma}{e_1\ \Rightarrow\ A}{\Gamma,\Theta} \quad \Gamma\ \dashv\ \text{Gen}(A)=A' \quad \expr{\Gamma,v:A'}{e_2\ \Rightarrow\ B}{\Delta}}{\expr{\Gamma}{v=e_1\ ;\ e_2}{\Delta}}$ [blue]+Statement+
   $\quad\quad$
   $\frac{\expr{\Gamma, x:A}{e_2 \Rightarrow A}{\Delta}}{\expr{\Gamma}{x\ ::\ A\ ;\ e_2}{\Delta}}$ [blue]+Signature+
   +
   +
   $\frac{\expr{\Gamma}{x\Rightarrow A}{\Gamma'} \quad \expr{\Gamma}{y\Rightarrow A'}{\Gamma'} \quad \expr{\Gamma}{A\ <:\ B}{\Delta}}{\expr{\Gamma}{[x,y\ \|\ \forall\ (x,y)\ \in\ \vec{xs}\]}{\Delta}}$ [blue]+List+
   +
   +
   $\frac{}{\expr{\Gamma}{() \Rightarrow 1}{\Gamma}}$ [green]+1l⇒+
   $\quad\quad$
   $\frac{(x:A) \in \Gamma}{\expr{\Gamma}{x\ \Rightarrow A}{\Gamma}}$ [green]+Var+
   $\quad\quad$
   +
   +
   $\frac{\expr{\Gamma,\ea,\eb,x:\ea}{e \Leftarrow \eb}{\Delta, x:\ea, \Theta}}{\expr{\Gamma}{\lambda x.e\ \Rightarrow\ \ea\rightarrow \eb}{\Delta}}$ [green]+→I⇒+
   $\quad\quad$
   $\frac{\expr{\Gamma}{e_1\ \Rightarrow\ A}{\Theta} \quad\quad \expr{\Theta}{[\Theta\]A \bullet e_2 \Rightarrow\Rightarrow C}{\Delta}}{\expr{\Gamma}{e_1 e_2 \Rightarrow C}{\Delta}}$ [green]+→E+
   $\quad\quad$
   $\frac{\Gamma\ \vdash\ A \quad\quad \expr{\Gamma}{e \Leftarrow A}{\Delta}}{\expr{\Gamma}{(e:A)\ \Rightarrow\ A}{\Delta}}$ [green]+Anno+
>| $\text{infer} :: \Gamma \rightarrow e \rightarrow (\Delta, A)$
|===

.check
|===
^| $\frac{}{\expr{\Gamma}{() \Leftarrow 1}{\Gamma}}$ [green]+1I+
   $\quad\quad$
   $\frac{\expr{\Gamma,x:A}{e \Leftarrow B}{\Delta,x:A,\Theta}}{\expr{\Gamma}{\lambda x.e \Leftarrow A \rightarrow B}{\Delta}}$ [green]+→I+
   $\quad\quad$
   $\frac{\expr{\Gamma,\alpha}{e \Leftarrow A}{\Delta,\alpha,\Theta}}{\expr{\Gamma}{e \Leftarrow \forall \alpha . A}{\Delta}}$ [green]+∀I+
   $\quad\quad$
   $\frac{\expr{\Gamma}{e \Rightarrow A}{\Theta} \quad\quad \expr{\Theta}{[\Theta\]A\ <:\ [\Theta\]B}{\Delta}}{\expr{\Gamma}{e \Leftarrow B}{\Delta}}$ [green]+Sub+
   $\quad\quad$
>| $\text{check} :: \Gamma \rightarrow e \rightarrow A \rightarrow (\Delta, B)$
|===

.derive
|===
^| $\frac{\expr{\Gamma[\ea_2,\ea_1,\ea=\ea_1 \rightarrow \ea_2\]}{e \Leftarrow\ \ea_1}{\Delta}}{\expr{\Gamma[\ea\]}{\ea\ \bullet\ e \Rightarrow\Rightarrow \ea_2}{\Delta}}$ [green]*latexmath:[\ea]*[green]+App+
   $\quad\quad$
   $\frac{\expr{\Gamma,\ea}{[\ea/\alpha\]A\ \bullet\ e \Rightarrow\Rightarrow C}{\Delta}}{\expr{\Gamma}{\forall\alpha . A\ \bullet\ e \Rightarrow\Rightarrow C}{\Delta}}$ [green]+∀App+
   $\quad\quad$
   $\frac{\expr{\Gamma}{e \Leftarrow A}{\Delta}}{\expr{\Gamma}{A \rightarrow C\ \bullet\ e \Rightarrow\Rightarrow C}{\Delta}}$  [green]+→App+
   $\quad\quad$
>| $\text{derive} :: \Gamma \rightarrow e \rightarrow A \rightarrow (\Delta, B)$
|===

[bibliography]
== References

bibliography::[]
